#!/bin/bash

echo "Removing shit..."

rm -rf applelogo ramdisk devicetree kernelcache* Firmware *.plist *.dmg *.raw *.prepatched *.patched *.dif *.ipsw *.json *.dfu *.img3 .fseventsd .DS_Store ._* asr*

echo "Done :P"

