#!/bin/bash

echo "Removing shit..."

rm -f applelogo ramdisk devicetree
rm -rf Firmware
rm -f *.dmg
rm -f iBEC*
rm -f iBoot.*
rm -f LLB*
rm -f iBSS*
rm -f dtre*
rm -f kernelcache*
rm -f *.plist
rm -f *.img3
rm -f *.dec

echo "Done :P"
